swagger: '2.0'
info:
  title: 接口文档
  description: 接口文档
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
schemes:
  - http
  - https
paths:
  /ws/gpt/chat-*:
    get:
      tags:
        - openai
      summary: wss传输接口
      responses:
        '200':
          description: '[SUCCESS]获取成功'
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - api_key: [ ]
  /stream:
    get:
      tags:
        - openai
      summary: sse传输接口
      parameters:
        - name: question
          required: true
          type: string
          description: 提问
          in: query
        - name: key
          required: true
          type: string
          description: openai的token
          in: query
      responses:
        '200':
          description: '[SUCCESS]获取成功'
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - api_key: [ ]
  /image:
    post:
      tags:
        - openai
      summary: 绘图接口
      parameters:
        - name: question
          required: true
          type: string
          description: 提问
          in: formData
        - name: key
          required: true
          type: string
          description: openai的token
          in: query
      responses:
        '200':
          description: '[SUCCESS]获取成功'
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - api_key: [ ]
definitions:
  ImageResponse:
    title: 图片返回对象
    description: 图片返回对象
    type: array
    items:
      properties:
        url:
          description: 地址
          example: https://oaidalleapiprodscus.blob.core.windows.net/private/org-fbwizmwiG
          type: string
      type: object
  ApiResponse:
    title: 接口返回对象
    description: 接口返回对象
    properties:
      err_code:
        $ref: '#/definitions/errCode'
      err_msg:
        $ref: '#/definitions/errMsg'
      payload:
        $ref: '#/definitions/payload'
    type: object
  errCode:
    type: integer
    description: errCode
    example: 0
  errMsg:
    type: string
    description: errMsg
    example: "成功"
  payload:
    type: array
    description: 内容
    example: [ ]
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
